services:
  postgres:
    image: postgres:latest
    container_name: ecommerce_postgres
    restart: always
    environment:
      # feel free to change these values
      POSTGRES_USER: deep
      POSTGRES_PASSWORD: notsosecure
      POSTGRES_DB: ecommerce_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: ecommerce_redis
    restart: always
    ports:
      - '6379:6379'

volumes:
  postgres_data:
